[project]
name = "pasori-timecard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "libusb1==3.1.0",
    "loguru==0.7.2",
    "mypy==1.11.2",
    "mypy-extensions==1.0.0",
    "ndeflib==0.3.3",
    "nfcpy==1.0.4",
    "openpyxl>=3.1.5",
    "pydes==2.0.1",
    "pyserial==3.5",
    "pyside6==6.7.2",
    "pyside6-addons==6.7.2",
    "pyside6-essentials==6.7.2",
    "pytz==2024.1",
    "shiboken6==6.7.2",
    "sqlalchemy==2.0.34",
    "tomli==2.0.1",
    "types-pytz==2024.1.0.20240417",
    "typing-extensions==4.12.2",
]
